name: CI Pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build with Maven from the correct directory
      - name: Build with Maven (debug)
        run: mvn clean install -X # Enable full debug logging

      # Run tests with Maven from the correct directory
      - name: Run tests with Maven
        working-directory: ./ # Make sure to set the root directory
        run: mvn test
